[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]
solc_version = "0.8.20"
optimizer = true
optimizer_runs = 200
via_ir = false

[profile.default.fuzz]
runs = 1000
max_local_rejects = 10000
max_global_rejects = 10000

[profile.default.invariant]
runs = 1000
depth = 15
fail_on_revert = false

[profile.default.coverage]
enabled = true
report = ["text", "html", "lcov"]
exclude = [
    "test/",
    "script/",
    "lib/forge-std/src/",
    "lib/forge-std/lib/",
    "lib/openzeppelin-contracts/contracts/mocks/",
    "lib/erc721a/contracts/mocks/"
]

[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"
mainnet = "${MAINNET_RPC_URL}"

[etherscan]
sepolia = { key = "${ETHERSCAN_API_KEY}" }
mainnet = { key = "${ETHERSCAN_API_KEY}" } 